# Generated by Django 4.1.3 on 2022-11-21 19:04

from django.db import migrations, models
import django.db.models.deletion
import musicas.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_artista', models.CharField(max_length=500)),
                ('local_show', models.CharField(max_length=500)),
                ('imagem', models.ImageField(upload_to='midia/')),
            ],
        ),
        migrations.CreateModel(
            name='Faixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='musics/', validators=[musicas.validators.validate_is_audio])),
                ('time_length', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musicas.artista')),
            ],
        ),
    ]
