"""
Django settings for musicserver project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Caminho de onde esta nosso projeto
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# chave de seguranca do nosso projeto
SECRET_KEY = 'django-insecure-8ttn+zcpr!@8(s7c76&*)j4ug@vqwxf95i(e8(&6j7#6+nful1'

# mudancas no nosso codigo se reflete no navegador local
DEBUG = True

# hosts permitidos para rodar nosso projeto
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'musicas',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# Base onde estao os links que comandam nosso site
ROOT_URLCONF = 'musicserver.urls' #esta reencaminhando para links secundarios de cada app

# local dos projetos de backend, css, html etc...
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'musicas.context.lista_musicas',
                'musicas.context.lista_forro',
            ],
        },
    },
]


# servidor
WSGI_APPLICATION = 'musicserver.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

#local do banco de dados, por padrao é o sqlite, mas abaixo mudamos para mysql
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'musicserver',
        'USER': 'daniellsamorim',
        'PASSWORD': 'dsaasd',
        'HOST':'localhost',
        'PORT':'3306',
    }
}


# Validadores de senhas do django
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

# linguagem da pagina
LANGUAGE_CODE = 'pt-br'
# localizacao
TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# local dos arquivos estaticos (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/' #so a url para essa pasta
MEDIA_URL = 'media/' #so a url para essa pasta

MEDIA_ROOT = BASE_DIR / 'media' #crie a pasta no projeto

STATICFILES_DIRS = [
    BASE_DIR / 'static'
] #crie a pasta no projeto

# Definicao de chaves primarias do banco de dados (cria id automaticamente)
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
